import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { applyRepayment, assertTransition, calculateLoanTerms, LOAN_STATUS } from './loan-engine.js';
import { HttpError, json, readJson, securityHeaders } from './http.js';
import { clearSessionCookie, parseCookies, randomToken, sessionCookie, verifyPassword } from './security.js';

const publicDirectory = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../public');
const mutatingMethods = new Set(['POST', 'PUT', 'PATCH', 'DELETE']);
const mimeTypes = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8', '.svg': 'image/svg+xml' };
const rolePermissions = Object.freeze({ ADMIN: ['*'], LOAN_OFFICER: ['customers:read','customers:create','loans:read','loans:create','loans:submit','payments:create'], APPROVER: ['customers:read','loans:read','loans:approve','loans:decline'], CASHIER: ['customers:read','loans:read','loans:disburse','payments:create'] });
const hasPermission=(u,p)=>(rolePermissions[u.role]??[]).some(x=>x==='*'||x===p);
function assertPermission(user, permission){if(!hasPermission(user,permission))throw new HttpError(403,'You do not have permission to perform this action.')}
const publicUser=u=>({id:u.id,name:u.name,email:u.email,role:u.role,branchId:u.branchId,institutionId:u.institutionId});
function text(value,field,{required=true,max=200}={}){const v=String(value??'').trim();if(required&&!v)throw new HttpError(400,`${field} is required.`);if(v.length>max)throw new HttpError(400,`${field} cannot exceed ${max} characters.`);return v}
function positive(value,field){const n=Number(value);if(!Number.isInteger(n)||n<=0)throw new HttpError(400,`${field} must be a positive integer.`);return n}
function audit(data,user,action,entityType,entityId,details={}){data.auditLogs.unshift({id:crypto.randomUUID(),institutionId:user.institutionId,userId:user.id,userName:user.name,action,entityType,entityId,details,createdAt:new Date().toISOString()});data.auditLogs=data.auditLogs.slice(0,5000)}
async function authenticate(req,db){const token=parseCookies(req.headers.cookie).giffcash_session;if(!token)return null;const data=db.read();const session=data.sessions.find(s=>s.token===token&&new Date(s.expiresAt).getTime()>Date.now());if(!session)return null;const user=data.users.find(u=>u.id===session.userId&&u.active);return user?{user,session}:null}
function requireAuth(auth){if(!auth)throw new HttpError(401,'Authentication is required.');return auth}
function requireCsrf(req,auth){if(!mutatingMethods.has(req.method)||req.url.startsWith('/api/auth/login'))return;const supplied=req.headers['x-csrf-token'];if(!auth||!supplied||supplied!==auth.session.csrfToken)throw new HttpError(403,'Invalid CSRF token.')}
function nextSequence(items,field,prefix){const max=items.reduce((m,i)=>{const match=String(i[field]??'').match(/(\d+)$/);return Math.max(m,match?Number(match[1]):0)},0);return`${prefix}-${String(max+1).padStart(6,'0')}`}
function loanView(loan,data){const customer=data.customers.find(c=>c.id===loan.customerId);return{...loan,customerName:customer?.fullName??'Unknown customer',outstandingPesewas:Math.max(0,loan.totalDuePesewas-loan.totalPaidPesewas)}}
async function serveStatic(pathname,res){const requested=pathname==='/'?'/index.html':pathname;const filePath=path.resolve(publicDirectory,`.${requested}`);if(!filePath.startsWith(publicDirectory))throw new HttpError(403,'Forbidden.');try{const content=await fs.readFile(filePath);res.writeHead(200,{'Content-Type':mimeTypes[path.extname(filePath)]??'application/octet-stream','Content-Length':content.length,...securityHeaders()});res.end(content)}catch(error){if(error.code==='ENOENT')throw new HttpError(404,'Not found.');throw error}}
export function createApp({db,config}){return async function handler(req,res){Object.entries(securityHeaders()).forEach(([n,v])=>res.setHeader(n,v));try{const url=new URL(req.url,`http://${req.headers.host??'localhost'}`);const pathname=url.pathname;const auth=await authenticate(req,db);requireCsrf(req,auth);
if(pathname==='/api/health'&&req.method==='GET')return json(res,200,{status:'ok',service:'giffcash',timestamp:new Date().toISOString()});
if(pathname==='/api/auth/login'&&req.method==='POST'){const body=await readJson(req);const email=text(body.email,'Email').toLowerCase();const password=text(body.password,'Password',{max:500});const data=db.read();const user=data.users.find(u=>u.email.toLowerCase()===email&&u.active);if(!user||!(await verifyPassword(password,user.passwordHash)))throw new HttpError(401,'Invalid email or password.');const token=randomToken(),csrfToken=randomToken(24),expiresAt=new Date(Date.now()+config.sessionTtlMs).toISOString();await db.update(d=>{d.sessions=d.sessions.filter(s=>new Date(s.expiresAt).getTime()>Date.now());d.sessions.push({id:crypto.randomUUID(),userId:user.id,token,csrfToken,expiresAt,createdAt:new Date().toISOString()});audit(d,user,'AUTH_LOGIN','USER',user.id)});return json(res,200,{user:publicUser(user),csrfToken},{'Set-Cookie':sessionCookie(token,{secure:config.cookieSecure,maxAgeSeconds:Math.floor(config.sessionTtlMs/1000)})})}
if(pathname==='/api/auth/logout'&&req.method==='POST'){const current=requireAuth(auth);await db.update(d=>{d.sessions=d.sessions.filter(s=>s.id!==current.session.id);audit(d,current.user,'AUTH_LOGOUT','USER',current.user.id)});return json(res,200,{ok:true},{'Set-Cookie':clearSessionCookie({secure:config.cookieSecure})})}
if(pathname==='/api/auth/me'&&req.method==='GET'){const c=requireAuth(auth);return json(res,200,{user:publicUser(c.user),csrfToken:c.session.csrfToken})}
if(pathname==='/api/dashboard'&&req.method==='GET'){const{user}=requireAuth(auth),data=db.read(),customers=data.customers.filter(x=>x.institutionId===user.institutionId),loans=data.loans.filter(x=>x.institutionId===user.institutionId),payments=data.payments.filter(x=>x.institutionId===user.institutionId),active=['DISBURSED','ACTIVE'];return json(res,200,{counts:{customers:customers.length,pendingApplications:loans.filter(x=>x.status==='SUBMITTED').length,activeLoans:loans.filter(x=>active.includes(x.status)).length,portfolioPesewas:loans.filter(x=>active.includes(x.status)).reduce((s,x)=>s+Math.max(0,x.totalDuePesewas-x.totalPaidPesewas),0),collectedPesewas:payments.reduce((s,x)=>s+x.amountPesewas,0)},recentLoans:loans.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,5).map(x=>loanView(x,data))})}
if(pathname==='/api/customers'&&req.method==='GET'){const{user}=requireAuth(auth);assertPermission(user,'customers:read');const q=(url.searchParams.get('q')??'').trim().toLowerCase(),customers=db.read().customers.filter(x=>x.institutionId===user.institutionId).filter(x=>!q||[x.fullName,x.phone,x.customerNumber,x.nationalId].some(v=>String(v).toLowerCase().includes(q))).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));return json(res,200,{customers})}
if(pathname==='/api/customers'&&req.method==='POST'){const{user}=requireAuth(auth);assertPermission(user,'customers:create');const body=await readJson(req),fullName=text(body.fullName,'Full name'),phone=text(body.phone,'Phone',{max:30}),nationalId=text(body.nationalId,'National ID',{max:80}),email=text(body.email,'Email',{required:false,max:200}).toLowerCase(),occupation=text(body.occupation,'Occupation',{required:false}),monthlyIncomePesewas=Number(body.monthlyIncomePesewas??0);if(!Number.isInteger(monthlyIncomePesewas)||monthlyIncomePesewas<0)throw new HttpError(400,'Monthly income must be a non-negative integer.');const customer=await db.update(d=>{if(d.customers.some(x=>x.institutionId===user.institutionId&&(x.nationalId.toLowerCase()===nationalId.toLowerCase()||x.phone===phone)))throw new HttpError(409,'A customer with this National ID or phone already exists.');const t=new Date().toISOString(),r={id:crypto.randomUUID(),institutionId:user.institutionId,branchId:user.branchId,customerNumber:nextSequence(d.customers,'customerNumber','CUS'),fullName,phone,email,nationalId,occupation,monthlyIncomePesewas,status:'ACTIVE',createdAt:t,updatedAt:t};d.customers.push(r);audit(d,user,'CUSTOMER_CREATED','CUSTOMER',r.id,{customerNumber:r.customerNumber});return r});return json(res,201,{customer})}
if(pathname==='/api/loans'&&req.method==='GET'){const{user}=requireAuth(auth);assertPermission(user,'loans:read');const data=db.read();return json(res,200,{loans:data.loans.filter(x=>x.institutionId===user.institutionId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(x=>loanView(x,data))})}
if(pathname==='/api/loans'&&req.method==='POST'){const{user}=requireAuth(auth);assertPermission(user,'loans:create');const body=await readJson(req),customerId=text(body.customerId,'Customer'),purpose=text(body.purpose,'Purpose',{max:500}),principalPesewas=positive(body.principalPesewas,'Principal'),annualRatePercent=Number(body.annualRatePercent),termMonths=positive(body.termMonths,'Term');let terms;try{terms=calculateLoanTerms(principalPesewas,annualRatePercent,termMonths)}catch(e){throw new HttpError(400,e.message)}const loan=await db.update(d=>{if(!d.customers.some(x=>x.id===customerId&&x.institutionId===user.institutionId))throw new HttpError(404,'Customer not found.');const t=new Date().toISOString(),r={id:crypto.randomUUID(),institutionId:user.institutionId,branchId:user.branchId,applicationNumber:nextSequence(d.loans,'applicationNumber','APP'),customerId,purpose,status:'DRAFT',annualRatePercent,termMonths,...terms,totalPaidPesewas:0,createdBy:user.id,submittedAt:null,approvedAt:null,disbursedAt:null,createdAt:t,updatedAt:t};d.loans.push(r);audit(d,user,'LOAN_CREATED','LOAN',r.id,{applicationNumber:r.applicationNumber});return r});return json(res,201,{loan})}
const match=pathname.match(/^\/api\/loans\/([^/]+)\/(submit|approve|decline|disburse|repay)$/);if(match&&req.method==='POST'){const{user}=requireAuth(auth),[,loanId,action]=match,permission={submit:'loans:submit',approve:'loans:approve',decline:'loans:decline',disburse:'loans:disburse',repay:'payments:create'}[action];assertPermission(user,permission);const body=await readJson(req);const result=await db.update(d=>{const loan=d.loans.find(x=>x.id===loanId&&x.institutionId===user.institutionId);if(!loan)throw new HttpError(404,'Loan not found.');const t=new Date().toISOString();if(action==='submit'){try{assertTransition(loan.status,LOAN_STATUS.SUBMITTED)}catch(e){throw new HttpError(409,e.message)}loan.status='SUBMITTED';loan.submittedAt=t}else if(action==='approve'){try{assertTransition(loan.status,LOAN_STATUS.APPROVED)}catch(e){throw new HttpError(409,e.message)}loan.status='APPROVED';loan.approvedAt=t;loan.approvedBy=user.id}else if(action==='decline'){try{assertTransition(loan.status,LOAN_STATUS.DECLINED)}catch(e){throw new HttpError(409,e.message)}loan.status='DECLINED';loan.declineReason=text(body.reason,'Decline reason',{max:500});loan.declinedAt=t}else if(action==='disburse'){try{assertTransition(loan.status,LOAN_STATUS.DISBURSED)}catch(e){throw new HttpError(409,e.message)}loan.status='DISBURSED';loan.disbursedAt=t}else{const amountPesewas=positive(body.amountPesewas,'Repayment amount');let repayment;try{repayment=applyRepayment(loan,amountPesewas)}catch(e){throw new HttpError(409,e.message)}Object.assign(loan,repayment);d.payments.push({id:crypto.randomUUID(),institutionId:user.institutionId,branchId:user.branchId,receiptNumber:nextSequence(d.payments,'receiptNumber','RCT'),loanId:loan.id,customerId:loan.customerId,amountPesewas,channel:text(body.channel,'Channel',{required:false,max:30})||'CASH',receivedBy:user.id,createdAt:t})}loan.updatedAt=t;audit(d,user,`LOAN_${action.toUpperCase()}`,'LOAN',loan.id,action==='repay'?{amountPesewas:Number(body.amountPesewas)}:{});return loanView(loan,d)});return json(res,200,{loan:result})}
if(pathname==='/api/audit'&&req.method==='GET'){const{user}=requireAuth(auth);if(user.role!=='ADMIN')throw new HttpError(403,'Only administrators can view audit logs.');return json(res,200,{logs:db.read().auditLogs.filter(x=>x.institutionId===user.institutionId).slice(0,200)})}
if(pathname.startsWith('/api/'))throw new HttpError(404,'API endpoint not found.');return await serveStatic(pathname,res)}catch(error){const status=error instanceof HttpError?error.status:500;if(status===500)console.error(error);if(!res.headersSent)return json(res,status,{error:error.message??'Internal server error.',details:error.details});res.end()}}}
